### PR TITLE
nature comm (romeo_1488)

### PR DESCRIPTION
**Pull request by vivekbhr**

### CODE REVIEW

**Comment by vivekbhr** [comment]
@jpolka oh sorry I think we both pushed the fix at the same time :)

**Comment by jpolka** [comment]
Thanks so much Vivek, I see you are addressing the colon issue! I was just making another edit to put quotes around some of your other entries which should fix the problem, but I can wait for you to finish.

**Comment by vivekbhr** [comment]
I think it should only be the colons (I converted them to *-* ) but if not I would add the quotes instead.

**Comment by vivekbhr** [comment]
@jpolka All green! 

BTW I just realized that I was using the gitter channel from the readme to chat about this, but it was apparently set up only for the mozilla sprint. Shall I rather use one of the slack channels instead?

**Comment by jpolka** [comment]
Thanks so much, Vivek! We are trying to figure out a better way to communicate about this long term since it is not just an ASAPbio project. If it's ok with you I can also loop you into emails about the project?

**Comment by dhimmel** [comment]
Thanks @vivekbhr for the contribution! Looks like you got the hang of things.

> BTW I just realized that I was using the gitter channel from the readme to chat about this, but it was apparently set up only for the mozilla sprint. Shall I rather use one of the slack channels instead?

What type of communication? Preferably we do as much communication as possible via GitHub, especially if it's related to a pull request. I am very wary of non-public platforms, such as slack, since they're basically a black hole where it's very hard to find discussion in the future.

**Comment by vivekbhr** [comment]
@dhimmel I meant communication about this project. I'll use issues to raise questions/discussions for now. @jpolka I am ok with emails or with a gitter channel, whatever you find suitable.

**Pull request merged**
