### PR TITLE
romeo_54 (Nature publishing group)

### PR DESCRIPTION
**Pull request by vivekbhr**
Since there are no separate yamls for Nature methods, Nature Genetics and NSMB, I think this PR closes all of them.

### CODE REVIEW

**Comment by vivekbhr** [comment]
actually, even more. since I am not finding yamls for any of the journals mentioned under `journals` field. Does that mean this PR closes all of those?

**Comment by jpolka** [comment]
Hi @vivekbhr, thank you so much for this! These edits look great. I just added the urls where I think you pulled the policies from. And yes, romeo_54.yml should cover all of those journals. 

(Paging @dhimmel before I merge  as I recall we had some issues with merging from someone's master branch rather than a patch in the past...?)

**Comment by dhimmel** [comment]
> romeo_54.yml should cover all of those journals listed under journals: but not child-journals:

The idea is that the fields in `romeo_54.yml` apply to all of the listed journals under `journals`. The fields will also apply to the journals under `child-journals`, unless overridden by a more specific child policy.

> (Paging @dhimmel before I merge as I recall we had some issues with merging from someone's master branch rather than a patch in the past...?)

As long as the "files changed" for a pull request looks good (and the CI is passing), you can always merge it. The only issue with @vivekbhr making a PR from his master branch is that it can cause issues for future pull requests he creates. Just make sure to start any future pull requests from the latest repository version and not whatever version your `master` branch is at currently.

**Comment by vivekbhr** [comment]
@dhimmel @jpolka no worries I always pull before I push :)

**Pull request merged**
